### ISSUE TITLE
"Unable to set Remote Control" when starting container

### ISSUE THREAD

**Issue by fmauch** [urmahp/ursim_docker#4] opened 2021-07-22 11:09 UTC
When starting the container and connecting to the GUI the first time I get an error popup "Unable to set Remote Control". When enabling Remote Control mode in the settings I can re-raise this popup with switching between local control and remote control. The popup gets raised each time I switch, no matter whether I switch to or from remote control mode.

**Comment by urmahp** [comment] 2021-08-09 09:19
I don't think this is an issue with the docker image, but its an issue with the simulator, because I also see the issue when running the simulator on my local machine. But I will try to see if I can figure out where the issue is.

**Comment by urmahp** [comment] 2021-08-12 06:57
This is fixed with #6

**Closed by urmahp** 2021-08-12 06:57 UTC
